version: '3.8'
services:
  app:
    container_name: node_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://fiap:fiap123@mongo:27017/restaurant-project-db?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    container_name: mongo_db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiap
      - MONGO_INITDB_ROOT_PASSWORD=fiap123
      - MONGO_INITDB_DATABASE=restaurant-project-db
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local